apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: demo.yaml
spec:
  flows:
    - route:
        from:
          uri: esb
          steps:
            - to:
                uri: atlasmap